# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/string-direction/all/string-direction.rbi
#
# string-direction-1.2.1
module StringDirection
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
  def self.reset_configuration; end
end
class StringDirection::Configuration
  def default_strategies; end
  def default_strategies=(arg0); end
  def initialize; end
  def rtl_scripts; end
  def rtl_scripts=(arg0); end
  def string_methods_strategies; end
  def string_methods_strategies=(arg0); end
end
class StringDirection::Detector
  def bidi; end
  def bidi?(string); end
  def direction(string); end
  def infer_strategy_class_name(strategy); end
  def initialize(*strategies); end
  def initialize_strategies(strategies); end
  def ltr; end
  def ltr?(string); end
  def rtl; end
  def rtl?(string); end
  def strategies; end
  def strategies=(arg0); end
end
class StringDirection::Strategy
  def bidi; end
  def ltr; end
  def rtl; end
  def run(string); end
end
class StringDirection::MarksStrategy < StringDirection::Strategy
  def ltr_mark?(string); end
  def rtl_mark?(string); end
  def run(string); end
end
class StringDirection::CharactersStrategy < StringDirection::Strategy
  def ltr_characters?(string); end
  def ltr_regex; end
  def rtl_characters?(string); end
  def rtl_regex; end
  def rtl_script_character_classes; end
  def rtl_scripts; end
  def run(string); end
end
class StringDirection::DominantStrategy < StringDirection::CharactersStrategy
  def chars_count(string, regex); end
  def run(string); end
end
module StringDirection::StringMethods
  def bidi?; end
  def direction; end
  def ltr?; end
  def rtl?; end
  def string_direction_detector; end
  def string_direction_strategies; end
end
